title: Default

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: layout
            fieldsets:
              - heading
              - text
              - accordion
              - image
              - list
              - gallery
              - button
              - spacer
              - video
            settings:
              fields:
                class:
                  type: text
                  width: 1/2
                id:
                  type: text
                  width: 1/2
                image:
                  label: Background image
                  type: files
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files
