title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: layout
            fieldsets:
              - heading
              - text
              - image
              - list
              - gallery
            layouts:
              - "1/1"
              - "1/2, 1/2"
              - "1/3, 2/3"
              - "1/4, 1/4, 1/4, 1/4"
              - "1/1, 1/3, 2/3"
              - "1/1, 2/3, 1/3"
              - "1/2, 1/2, 1/3, 1/3, 1/3"
              - "1/1, 1/4, 1/4, 1/4, 1/4"
              - "1/1, 1/2, 1/2"
              - "1/1, 1/3, 1/3, 1/3"
              - "1/1, 1/1, 1/4, 1/4, 1/4, 1/4"
              - "1/1, 1/2, 1/2, 1/4, 1/4, 1/4, 1/4"
            settings:
              fields:
                class:
                  type: text
                  width: 1/2
                id:
                  type: text
                  width: 1/2
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files
